FROM tensorflow/tensorflow:latest-gpu-py3
ADD ["https://github.com/opencv/opencv/archive/3.3.0.tar.gz", "."]
RUN apt-get update \
    && apt-get install -y build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python3.5-dev \
    && rm -rf /var/lib/apt/lists/*
RUN tar -zxvf 3.3.0.tar.gz \
    && cd opencv-3.3.0 \
    && mkdir build \
    && cd build \
    && cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_CUDA=OFF -D BUILD_opencv_gpu=OFF -D CMAKE_INSTALL_PREFIX=/usr/local .. \
    && make -j$(nproc --all) \
    && make install \
    && cd /notebooks \
    && rm -rf 3.3.0.tar.gz opencv-3.3.0
